
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.jflex_cup.graficadorcup;

import java_cup.runtime.*;
import com.example.jflex_cup.graficadorflex.EjecutarLexico;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class EjecutarCup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ejecutarsym.class;
}

  /** Default constructor. */
  @Deprecated
  public EjecutarCup() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public EjecutarCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public EjecutarCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\004\004\004\001\002\000\004\006\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\010\010\001\002\000\004\005\011\001\002\000" +
    "\004\007\012\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$EjecutarCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$EjecutarCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$EjecutarCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public EjecutarCup(EjecutarLexico lexer) {
        super(lexer);
    }

    public void report_error(String message, Object info) {
        System.out.println("public void report_error");
    }

    public void report_fatal_error(String message, Object info) {
        System.out.println("public void report_fatal_error");
    }

    public void syntax_error(Symbol cur_token) {
        System.out.println("El error es el simbolo: " + sym.terminalNames[cur_token.sym]);
        System.out.println(String.format("En la posicion: %d, %d", cur_token.left, cur_token.right));
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
        if (cur_token.sym == ejecutarsym.EOF) {
            System.out.println("public void unrecoveredsyntax_error");
        }
    }

    private List<String> graficasEjecutar = new ArrayList<>();

    private void agregarGraficaEjecutar(String cadena){
        graficasEjecutar.add(cadena);
    }

    public List<String> getGraficasEjecutar(){
        return this.graficasEjecutar;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$EjecutarCup$actions {
  private final EjecutarCup parser;

  /** Constructor */
  CUP$EjecutarCup$actions(EjecutarCup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$EjecutarCup$do_action_part00000000(
    int                        CUP$EjecutarCup$act_num,
    java_cup.runtime.lr_parser CUP$EjecutarCup$parser,
    java.util.Stack            CUP$EjecutarCup$stack,
    int                        CUP$EjecutarCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$EjecutarCup$result;

      /* select the action based on the action number */
      switch (CUP$EjecutarCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= EJ EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-1)).value;
		RESULT = start_val;
              CUP$EjecutarCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-1)), ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$EjecutarCup$parser.done_parsing();
          return CUP$EjecutarCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // EJ ::= EJECUTAR PARENTESIS_A CADENA PARENTESIS_C PUNTO_COMA 
            {
              Object RESULT =null;
		int cadenaleft = ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-2)).left;
		int cadenaright = ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-2)).right;
		String cadena = (String)((java_cup.runtime.Symbol) CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-2)).value;
		agregarGraficaEjecutar(cadena);
              CUP$EjecutarCup$result = parser.getSymbolFactory().newSymbol("EJ",0, ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.elementAt(CUP$EjecutarCup$top-4)), ((java_cup.runtime.Symbol)CUP$EjecutarCup$stack.peek()), RESULT);
            }
          return CUP$EjecutarCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$EjecutarCup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$EjecutarCup$do_action(
    int                        CUP$EjecutarCup$act_num,
    java_cup.runtime.lr_parser CUP$EjecutarCup$parser,
    java.util.Stack            CUP$EjecutarCup$stack,
    int                        CUP$EjecutarCup$top)
    throws java.lang.Exception
    {
              return CUP$EjecutarCup$do_action_part00000000(
                               CUP$EjecutarCup$act_num,
                               CUP$EjecutarCup$parser,
                               CUP$EjecutarCup$stack,
                               CUP$EjecutarCup$top);
    }
}

}
