
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.jflex_cup.graficadorcup;

/** CUP generated class containing symbol constants. */
public class ejecutarsym {
  /* terminals */
  public static final int error = 1;
  public static final int PUNTO_COMA = 5;
  public static final int PARENTESIS_C = 3;
  public static final int PARENTESIS_A = 4;
  public static final int EJECUTAR = 2;
  public static final int EOF = 0;
  public static final int CADENA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EJECUTAR",
  "PARENTESIS_C",
  "PARENTESIS_A",
  "PUNTO_COMA",
  "CADENA"
  };
}

