
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.jflex_cup.graficadorcup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 19;
  public static final int CADENA = 29;
  public static final int DECIMAL = 31;
  public static final int DIVISION = 20;
  public static final int SUMA = 17;
  public static final int ETIQUETAS = 9;
  public static final int DOS_PUNTOS = 21;
  public static final int TIPO = 12;
  public static final int PORCENTAJE = 14;
  public static final int BARRAS = 3;
  public static final int VALORES = 10;
  public static final int COMA = 5;
  public static final int EOF = 0;
  public static final int TOTAL = 15;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int EXTRA = 16;
  public static final int CANTIDAD = 13;
  public static final int PARENTESIS_C = 24;
  public static final int error = 1;
  public static final int LLAVE_C = 28;
  public static final int PARENTESIS_A = 23;
  public static final int LLAVE_A = 27;
  public static final int PUNTO_COMA = 22;
  public static final int EJEY = 8;
  public static final int EJEX = 7;
  public static final int ENTERO = 30;
  public static final int CORCHETE_C = 26;
  public static final int CORCHETE_A = 25;
  public static final int UNIR = 11;
  public static final int TITULO = 6;
  public static final int RESTA = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "COMA",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "TOTAL",
  "EXTRA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "LLAVE_A",
  "LLAVE_C",
  "CADENA",
  "ENTERO",
  "DECIMAL"
  };
}

